# Site settings
title: Dublin Aikikai
email: info@dublinaikido.com
url: https://dublinaikido.com
description: "We emphasise movement, contact and freedom. Our classes are constructive, open and vigorous."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  #links: '#219ab3'
  links: '#ef8900'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/DublinAikido

# Build settings
markdown: kramdown
permalink: pretty

baseurl: /DublinAikido